parameters:
#    vocationet.example.class: AT\vocationetBundle\Example

services:
    security:
        class: AT\vocationetBundle\Services\SecurityService
        arguments: ["@doctrine", "@session"]
    mail:
        class: AT\vocationetBundle\Services\MailService
        arguments: ["@mailer", "@templating"]
    validate:
        class: AT\vocationetBundle\Services\ValidateService
        arguments: ["@validator"]
    facebook:
        class: AT\vocationetBundle\Services\FacebookService
        arguments: [%facebook_app_id%, %facebook_app_secret%, "@service_container"]
    linkedin:
        class: AT\vocationetBundle\Services\LinkedinService
        arguments: [%linkedin_api_key%, %linkedin_secret_key%, "@service_container"]
    perfil:
        class: AT\vocationetBundle\Services\PerfilService
        arguments: ["@doctrine", "@translator"]
    usuarios:
        class: AT\vocationetBundle\Services\UsuariosService
        arguments: ["@doctrine", "@session"]
    mensajes:
        class: AT\vocationetBundle\Services\MensajesService
        arguments: ["@service_container"]
    file:
        class: AT\vocationetBundle\Services\FileService
        arguments: ["@doctrine", "@session"]
       
