parameters:
#    vocationet.example.class: AT\vocationetBundle\Example

services:
    security:
        class: AT\vocationetBundle\Services\SecurityService
        arguments: ["@doctrine", "@session"]
    facebook:
        class: AT\vocationetBundle\Services\FacebookService
        arguments: [%facebook_app_id%, %facebook_app_secret%, "@service_container"]
    linkedin:
        class: AT\vocationetBundle\Services\LinkedinService
        arguments: [%linkedin_api_key%, %linkedin_secret_key%, "@service_container"]
    perfil:
        class: AT\vocationetBundle\Services\PerfilService
        arguments: ["@doctrine"]
    usuarios:
        class: AT\vocationetBundle\Services\UsuariosService
        arguments: ["@doctrine", "@session"]
       