parameters:
#    vocationet.example.class: AT\vocationetBundle\Example

services:
    security:
        class: AT\vocationetBundle\Services\SecurityService
        arguments: ["@doctrine", "@session"]
    perfil:
       class: AT\vocationetBundle\Services\PerfilService
       arguments: ["@doctrine"]

