parameters:
#    vocationet.example.class: AT\vocationetBundle\Example

services:
    security:
        class: AT\vocationetBundle\Services\SecurityService
        arguments: ["@doctrine", "@session"]
    facebook:
        class: AT\vocationetBundle\Services\FacebookService
        arguments: [%facebook_app_id%, %facebook_app_secret%, "@service_container"]
